### ISSUE TITLE
What is the difference between this version and the one on the website?

### ISSUE THREAD

**Issue by rjfnobre** [cavazos-lab/PolyBench-ACC#4]
Regarding the OpenCL and the CUDA implementations, what is the difference between this version and the one on the website?

http://web.cse.ohio-state.edu/~pouchet/software/polybench/GPU/

**Comment by rjfnobre** [comment]
And what about the OpenMP versions in this repository?

Were the pragmas manually added so that the OpenMP versions would have more performance than the original sequential C versions?
Or was some automatic paralelization tool used (such as PLUTO: http://pluto-compiler.sourceforge.net/) to decide where to put the OpenMP pragmas and/or apply some other transformations (such as loop tiling)?

Do the OpenMP versions scale well with the number of CPU cores?
Are the OpenMP versions faster with two CPU cores, versus the original sequential C versions?
I ask this because many times if one is not careful (at least in my experience) when using OpenMP, one ends with a poor implementation.

I searched for that information in the paper "Auto-tuning a High-Level Language Targeted to GPU
Codes" but I could not find it.

**Comment by sgrauerg** [comment]
The versions are similar for the OpenCL and CUDA implementations (the
benchmarks themselves should be the same), but the implementation on Github
is updated and is based off of PolyBench 3.2, contains more benchmarks, and
adds OpenACC and OpenMP implementations while the implementation at
http://web.cse.ohio-state.edu/~pouchet/software/polybench/GPU/ is based off
of PolyBench 2.0.

I'll note that the results presented in the paper "Auto-tuning a High-Level
Language Targeted to GPU Codes" used the older version (that was based on
PolyBench 2.0).

-Scott Grauer-Gray
sgrauerg@gmail.com

**Comment by sgrauerg** [comment]
I did not write the OpenMP versions (they were not part of the original
work presented in the paper), but I believe they were added manually and
should have better performance than the sequential versions and scale with
the number of CPU cores.

-Scott Grauer-Gray
sgrauerg@gmail.com
