### ISSUE TITLE
Software License?

### ISSUE THREAD

**Issue by jlgreathouse** [cavazos-lab/PolyBench-ACC#5]
Thanks for making this benchmark suite available!

Like my [question for FinanceBench](https://github.com/cavazos-lab/FinanceBench/issues/2), I'm looking to understand the license for PolyBench-ACC. I can't find a specified license in the git repo, so I figured I'd ask (and hopefully get an explicit license included in the repo).

The old versions of PolyBench/C (on which PolyBench/ACC is based) also appear to have this problem, but [the newest version](https://sourceforge.net/p/polybench/code/HEAD/tree/trunk/polybench-code/LICENSE.txt) uses a modified BSD license.

Is this also the case for PolyBench/ACC?

**Comment by sgrauerg6** [comment]
Hey,

Same as with FinanceBench, as far as I know there are no major issues/restrictions with others using the code, so can consider it to have the same modified BSD license as the newest version of Polybench.

-Scott

**Comment by willkill07** [comment]
3-clause BSD license is now explicitly added.
